<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ET-C02T91MYG8WN.local" name="com.qa.tests.LoginTest" tests="8" failures="2" timestamp="2021-03-22T17:23:50 IST" time="81.682" errors="0">
  <testcase name="unsuccessful_login_wrong_username" time="5.035" classname="com.qa.tests.LoginTest"/>
  <system-out/>
  <testcase name="unsuccessful_login_wrong_password_username" time="5.156" classname="com.qa.tests.LoginTest"/>
  <system-out/>
  <testcase name="unsuccessful_login_wrong_password_username" time="10.616" classname="com.qa.tests.LoginTest"/>
  <system-out/>
  <testcase name="unsuccessful_login_wrong_username" time="10.579" classname="com.qa.tests.LoginTest"/>
  <system-out/>
  <testcase name="unsuccessful_login_wrong_password" time="11.444" classname="com.qa.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.zzz]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.zzz]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.tests.LoginTest.unsuccessful_login_wrong_password(LoginTest.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- unsuccessful_login_wrong_password -->
  <system-out>
This is the sample screenshot <a href='/Users/vishnu.vardhan/Desktop/Appium-SauceLabs-Automation/Screenshots/iOS_iPhone/2021/03/22 17:22:44/LoginTest/unsuccessful_login_wrong_password.png'> <img src='/Users/vishnu.vardhan/Desktop/Appium-SauceLabs-Automation/Screenshots/iOS_iPhone/2021/03/22 17:22:44/LoginTest/unsuccessful_login_wrong_password.png' height='400' width='400'/> </a>  </system-out>
  <testcase name="successful_login" time="12.364" classname="com.qa.tests.LoginTest"/>
  <system-out/>
  <testcase name="successful_login" time="21.761" classname="com.qa.tests.LoginTest"/>
  <system-out/>
  <testcase name="unsuccessful_login_wrong_password" time="4.727" classname="com.qa.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.zzz]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.zzz]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.tests.LoginTest.unsuccessful_login_wrong_password(LoginTest.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- unsuccessful_login_wrong_password -->
  <system-out>
This is the sample screenshot <a href='/Users/vishnu.vardhan/Desktop/Appium-SauceLabs-Automation/Screenshots/Android_pixel2/2021/03/22 17:22:44/LoginTest/unsuccessful_login_wrong_password.png'> <img src='/Users/vishnu.vardhan/Desktop/Appium-SauceLabs-Automation/Screenshots/Android_pixel2/2021/03/22 17:22:44/LoginTest/unsuccessful_login_wrong_password.png' height='400' width='400'/> </a>  </system-out>
</testsuite> <!-- com.qa.tests.LoginTest -->
